### ISSUE TITLE
check, that cats resoures are mapped to scala Using.Releasable

### ISSUE THREAD

**Issue by rssh** [rssh/cps-async-connect#2]
Scala standard library define Using.Releasable 
given Using.Releasable[TestResource] 

Library-specific resources should be mapped to it. (i.e. should exist given Using.Releasable[cats.Resource]).  If such a given Rekeasable is not defined in the library, we can define it here.

Add tests, 
(example,  https://github.com/rssh/dotty-cps-async/blob/master/shared/src/test/scala/cps/TestCBS1ShiftUsing.scala
  something like this, with the difference that test Resource should be cats[monix/zio] resource and test framework is munit here)

**Comment by sideeffffect** [comment]
I don't think that `Using.Releasable` (from standard library) is relevant for `cats.Resource`. They both are designed to work with resources that need to be allocated and released, but do that differently, so `cats.Resource` won't work with Using.Releasable`.

But integration with `cats.Resource` (or `zio.Managed`) would still be enormously useful. Both have the `.use` method, just as `cats.Monad` (well, `cats.FlatMap`, to be precise) has `.flatMap`.
So I was thinking, that since `await`/`!` is translated by `cps-async-connect` to `.flatMap`, could `~` be translated to `.use`?

**Comment by rssh** [comment]
Let's think:

We have   `Resource[F,A].use[B](A =>F[B])`
What we want inside async: something like `CpsResourceExtension[Resource[F,A]].use[B](A=>B)`
cps transformer will modify call to f:A=>B. into call to use_async[A=>F[B]], so this will be something like
```
extension cpsResource[F,A](r: Resource[F,A])(using m:CpsTryMonad[F]):
    def use[B](f: A => B):  B =
         r.use( a => m.pure(a) ).   //. called when cps(code_f) === pure[B], i.e. f not include awaits

   inline def  use_async[B](f: A=>F[B]): F[B] =
        r.use(f).   // callen when cps(code_f). is async
     
```
  Looks like this will do all that we need, but need to recheck and write tests.

**Comment by rssh** [comment]
Another question:   can we change the syntax to avoid extra brackets around use arguments.  It's need investigations in terms of CpsAsync

**Comment by rssh** [comment]
Finally what's work:

```
transparent inline def using[F[_],A, B](r:Resource[F,A])(inline f: A=>B)(using m:CpsMonad[F], cm: MonadCancel[F,Throwable]): B =
     await(r.use(a => m.pure(f(a)) ))
```

Usage:  
```
 using(openFile){ buffer => .
     .... do something here, can insert awaits.
 }
```

**Comment by rssh** [comment]
(should add description to readme)

**Comment by sideeffffect** [comment]
What I had in mind is not
```scala
async[Task] {
    val r = makeWriterEmu()
    val ctr = await(Ref.make(0))
    using(r) { a => 
        val c0 = await(ctr.get)
        a.write(s"AAA-${c0}")
        await(ctr.update(_ + 1))
        val c1 = await(ctr.get)
        a.write(s"BBB-${c1}")
        (a, a.messages.toList, a.isClosed)
    }
}
```
That syntax has a significant downside: it causes nesting. Imagine, how would the code look, if you had to work with _multiple_ resources. It doesn't provide any advantage over calling directly `.use`.

Could `cps-async-connect` do something like
```scala
async[Task] {
    val r = makeWriterEmu()
    val ctr = await(Ref.make(0))
    val a = using(r)
    val c0 = await(ctr.get)
    a.write(s"AAA-${c0}")
    await(ctr.update(_ + 1))
    val c1 = await(ctr.get)
    a.write(s"BBB-${c1}")
    (a, a.messages.toList, a.isClosed)
}
```
Or even more preferably
```scala
async[Task] {
    val r = makeWriterEmu()
    val ctr = ! Ref.make(0)
    val a = ~ r
    val c0 = ! ctr.get
    a.write(s"AAA-${c0}")
    ! ctr.update(_ + 1)
    val c1 = ! ctr.get
    a.write(s"BBB-${c1}")
    (a, a.messages.toList, a.isClosed)
}
```
?
Thank you for your effort on this! :heart:

**Comment by rssh** [comment]
Сan notice that there is significantly much more magic than in automatic coloring.

Hmm,  we can't embed F in Resource[F,A],  but can embedd  F[A] into Resource[F,A].  So,  await will be enough, example:
```
async[[X]=>>Resource[IO,X]] {
      val reader = await(openFile(input))
      val writer = await(openFile(output))
      writer.writeAll(reader)
}
```

The trick is that our main monad is [X]=>>Resource[IO,X],  not IO

**Comment by sideeffffect** [comment]
Oh, I don't think we need to do anything like that. The point here is that `.use` (just like `.flatMap`) returns `IO`/`Task` (`.use doesn't return `Resource`).

**Comment by rssh** [comment]
btw, for now, we have the next syntax:

```
asyncScope[IO] {
     val reader = await(openFile(input))
      val writer = await(openFile(output))
      writer.writeAll(reader)
}
```

(asyncScope[IO] internally use async[[X]=>Resource[IO,X]]. but expose IO to the external world.

**Comment by sideeffffect** [comment]
Does that mean, that in `asyncScope` I can mix `IO` and `Resource[IO, *]`? As in
```scala
asyncScope[IO] {
  val reader = await(openFileIO(input))
  val writer = await(openFileResource(output))
  writer.writeAll(reader)
}
```

**Comment by rssh** [comment]
yes
